apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-o25f
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-o25f@sha256:2c88be378244135308eae46c757c3e0b4270132f67d049e1e4f8029553b1fb2d
        name: my-nodejs
        resources: {}
status: {}
